// -*- mode: c++ -*-
//
// $Id: label.h 4742 2013-01-27 15:33:30Z rafisol $

#ifndef DEBUG_H
#define DEBUG_H

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <iostream>
#include <fstream>
#include <string>

/**
 * Simple static class for debug output.
 *
 * Debug output is generated by using the DEBUGOUT macro. It will only
 * log output if:
 *
 * 1. the code was NOT compiled with -DNDEBUG
 *
 * 2. DEBUG::start() was called in the application.
 */
class DEBUG {
    private:
	static bool __initialized;
	static std::ofstream __file;

    public:
	static void start();
	static void end();
	static void out(const std::string& _o);
};

#ifndef NDEBUG
#define DEBUGOUT(x) (DEBUG::out(x))
#else
#define DEBUGOUT(x)
#endif // NDEBUG

#endif // DEBUG_H
